# Generated by Django 3.0 on 2020-05-19 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Flight', '0002_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookedby', to=settings.AUTH_USER_MODEL)),
                ('bookedfor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookedfor', to='Flight.Passenger')),
            ],
        ),
    ]
