# Generated by Django 3.0 on 2020-05-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0003_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='flight',
            field=models.ManyToManyField(blank=True, related_name='bookedflight', to='Flight.Flight'),
        ),
    ]
