# Generated by Django 3.0 on 2020-05-20 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0005_auto_20200520_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookedflight', to='Flight.Flight'),
        ),
    ]
