# Generated by Django 3.0 on 2020-07-01 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0006_auto_20200520_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 1)),
        ),
    ]
