# Generated by Django 3.0 on 2020-07-03 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0007_bookings_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 3)),
        ),
    ]
